{"frozen":{"name":"python3.7-zope.exceptions","shortDescription":"Exception interfaces and implementations","versionString":"4.3","homepage":"https://pypi.python.org/pypi/zope.exceptions","license":{"fullName":"Zope Public License 2.0","shortName":"zpl20","spdxId":"ZPL-2.0","url":"http://spdx.org/licenses/ZPL-2.0.html"},"versionNumberList":[4,3]},"flexible":{"sources":[{"git":"https://github.com/NixOS/nixpkgs.git","commit":"22091c912a38f2f9f8cb8efd612915a9346e57cb","attributePath":["python37Packages","zope_exceptions"],"position":"/nix/store/z9pm444cj6kmm2m01vf28xa94bakm7cm-22091c912a38f2f9f8cb8efd612915a9346e57cb.tar.gz/pkgs/development/python-modules/zope_exceptions/default.nix:22","date":"2019-03-01"}],"platforms":[{"kernel":{"_type":"kernel","execFormat":{"_type":"exec-format","name":"elf"},"families":{},"name":"linux"}},{"kernel":{"families":{"darwin":{"_type":"exec-format","name":"darwin"}}}}]}}