{"frozen":{"name":"python3.4-zope.exceptions","shortDescription":"Exception interfaces and implementations","versionString":"4.0.5","homepage":"http://pypi.python.org/pypi/zope.exceptions","license":{"fullName":"Zope Public License 2.0","shortName":"zpt20","spdxId":"ZPL-2.0","url":"http://spdx.org/licenses/ZPL-2.0"},"versionNumberList":[4,0,5]},"flexible":{"sources":[{"git":"https://github.com/NixOS/nixpkgs.git","commit":"6542c344bcf0077e7530a0e8f02034aa92b52b39","attributePath":["python34Packages","zope_exceptions"],"position":"/nix/store/f9gnvpp942xsz6y4wk5vyd5hrnmczz12-6542c344bcf0077e7530a0e8f02034aa92b52b39.tar.gz/pkgs/top-level/python-packages.nix:14919","date":"2015-08-08"}],"platforms":["i686-linux","x86_64-linux","armv5tel-linux","armv6l-linux","armv7l-linux","mips64el-linux","x86_64-darwin"]}}